module.exports = {
  api: null,
  service: null,
  port: null,
  host: null,
  entry: target => `./src/entry-${target}`,
  simpleEntry: `./src/mains.js`,
  defaultTitle: 'My app',
  favicon: './public/favicon.ico',
  error500Html: null,
  skipRequests: req => req.originalUrl === '/graphql',
  nodeExternalsWhitelist: [/\.css$/, /\?vue&type=style/, /^vuetify/, /^vue-cropperjs/],
  extendServer: null,
  // Paths
  distPath: null,
  templatePath: null,
  simpleTemplateName: 'indexs.html',
  serviceWorkerPath: null,
  directives: {},
}
